POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content": "User id of other note",
    "important": true,
    "userId": "60c20d5afbecaf38b47b9014"
}

###
POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
}